# Script: renv project setup.R

## using {renv} package environment setup for this project
# install.packages('renv',dependencies = TRUE)
library(renv)

# 1. Initialize environment for this specific project 
# Call renv::init() to start using renv in the current project. This will 
## Setup project infrastructure

renv::init()


# 2. Install required libraries for this environment and then run the scripts
renv::install('climaemet')
renv::install('here')
renv::install('dplyr')
renv::install('ggplot2')
renv::install('janitor')

# 3 Check status of your lockfile using renv::status() function:
## status() reports issues caused by inconsistencies across the project lockfile

renv::status()

# 4 After we have confirmed the code works as expected, we use renv::snapshot()
## To record the packages and their sourecs in the lockfile

renv::snapshot()

# 5. To replicate this project in any machine, once all outputs have been created
# restore() > Restore a project's dependencies from a lockfile, as previously generated by snapshot()
# renv::restore()